import type {
  ApiDefaultResponseType,
  StageLogGroupFormatKeys,
} from '../../resolver.types';

export const apiResponseStatusCode: Record<ApiDefaultResponseType, number | undefined> = {
  accessDenied: 401,
  apiConfigurationError: 500,
  authorizerConfigurationError: 500,
  authorizerFailure: 500,
  badRequestBody: 400,
  badRequestParameters: 500,
  default4xx: undefined,
  default5xx: undefined,
  expiredToken: 403,
  integrationFailure: 504,
  integrationTimeout: 504,
  invalidApiKey: 401,
  invalidSignature: 403,
  missingAuthenticationToken: 401,
  quotaExceeded: 429,
  requestTooLarge: 413,
  resourceNotFound: 404,
  throttled: 429,
  unauthorized: 401,
  unsupportedMediaType: 415,
  wafFiltered: 401,
};

export const apiResponseName: Record<ApiDefaultResponseType, string> = {
  accessDenied: 'ACCESS_DENIED',
  apiConfigurationError: 'API_CONFIGURATION_ERROR',
  authorizerConfigurationError: 'AUTHORIZER_CONFIGURATION_ERROR',
  authorizerFailure: 'AUTHORIZER_FAILURE',
  badRequestBody: 'BAD_REQUEST_BODY',
  badRequestParameters: 'BAD_REQUEST_PARAMETERS',
  default4xx: 'DEFAULT_4XX',
  default5xx: 'DEFAULT_5XX',
  expiredToken: 'EXPIRED_TOKEN',
  integrationFailure: 'INTEGRATION_FAILURE',
  integrationTimeout: 'INTEGRATION_TIMEOUT',
  invalidApiKey: 'INVALID_API_KEY',
  invalidSignature: 'INVALID_SIGNATURE',
  missingAuthenticationToken: 'MISSING_AUTHENTICATION_TOKEN',
  quotaExceeded: 'QUOTA_EXCEEDED',
  requestTooLarge: 'REQUEST_TOO_LARGE',
  resourceNotFound: 'RESOURCE_NOT_FOUND',
  throttled: 'THROTTLED',
  unauthorized: 'UNAUTHORIZED',
  unsupportedMediaType: 'UNSUPPORTED_MEDIA_TYPE',
  wafFiltered: 'WAF_FILTERED',
};

export const logFormatValues: Record<StageLogGroupFormatKeys, string> = {
  requestId: '$context.requestId',
  extendedRequestId: '$context.extendedRequestId',
  ip: '$context.identity.sourceIp',
  caller: '$context.identity.caller',
  user: '$context.identity.user',
  requestTime: '$context.requestTime',
  httpMethod: '$context.httpMethod',
  resourcePath: '$context.resourcePath',
  status: '$context.status',
  protocol: '$context.protocol',
  responseLength: '$context.responseLength',
};
